version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./screenshots:/usr/screenshots
  screen:
    build: ./screen-driver
    volumes:
      - ./screenshots:/usr/screenshots
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
    depends_on:
      - app
