version: "3.9"
services:
  app:
    image: eddwills95/umbrui:main
    # Allows building on the Pi easily
    # build: 
    #   context: ./umbrui
    volumes:
      - ./screenshots:/usr/screenshots
      - ${APP_DATA_DIR}/../../tor/data/web/hostname:/app/tor_hostname
    network_mode: host
  screen:
    image: eddwills95/umbrui-renderer:main
    volumes:
      - ./screenshots:/usr/screenshots
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
    depends_on:
      - app
