version: "3.9"
services:
  # fbcp:
  #   image: balenablocks/fbcp:waveshare35b-ili9486
  app:
    build: .
    volumes:
      - ./screenshots:/usr/screenshots
    devices:
      - /dev/tty:/dev/tty
    # depends_on:
    #   - fbcp
